/// Utility mapping for league flag emojis and display helpers.
class LeagueUtils {
  LeagueUtils._();

  static const _leagueFlags = {
    'Premier League': '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    'La Liga': '🇪🇸',
    'Bundesliga': '🇩🇪',
    'Serie A': '🇮🇹',
    'Ligue 1': '🇫🇷',
    'Ligue 1 CI': '🇨🇮',
    'UEFA Champions League': '🏆',
    'UEFA Europa League': '🏆',
    'UEFA Conference League': '🏆',
    'Coupe du Monde': '🌍',
    'Euro': '🇪🇺',
    'CAN': '🌍',
    'Liga Portugal': '🇵🇹',
    'Eredivisie': '🇳🇱',
    'Jupiler Pro League': '🇧🇪',
    'Super Lig': '🇹🇷',
    'Primeira Liga': '🇵🇹',
    'Championship': '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    'Scottish Premiership': '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    'Süper Lig': '🇹🇷',
    'MLS': '🇺🇸',
    'Liga MX': '🇲🇽',
    'Brasileirão': '🇧🇷',
    'A-League': '🇦🇺',
    'J-League': '🇯🇵',
    'K League': '🇰🇷',
    'Saudi Pro League': '🇸🇦',
    'Super League': '🇨🇭',
  };

  static const _countryFlags = {
    'England': '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    'Spain': '🇪🇸',
    'Germany': '🇩🇪',
    'Italy': '🇮🇹',
    'France': '🇫🇷',
    'Portugal': '🇵🇹',
    'Netherlands': '🇳🇱',
    'Belgium': '🇧🇪',
    'Turkey': '🇹🇷',
    'Scotland': '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    'USA': '🇺🇸',
    'Mexico': '🇲🇽',
    'Brazil': '🇧🇷',
    'Argentina': '🇦🇷',
    'Australia': '🇦🇺',
    'Japan': '🇯🇵',
    'South-Korea': '🇰🇷',
    'Saudi-Arabia': '🇸🇦',
    'China': '🇨🇳',
    'Ivory Coast': '🇨🇮',
    'World': '🌍',
    'Europe': '🇪🇺',
    'Africa': '🌍',
    'South-America': '🌎',
    'North-Central-America': '🌎',
    'Asia': '🌏',
    'Greece': '🇬🇷',
    'Switzerland': '🇨🇭',
    'Austria': '🇦🇹',
    'Denmark': '🇩🇰',
    'Norway': '🇳🇴',
    'Sweden': '🇸🇪',
    'Finland': '🇫🇮',
    'Poland': '🇵🇱',
    'Czech-Republic': '🇨🇿',
    'Croatia': '🇭🇷',
    'Serbia': '🇷🇸',
    'Romania': '🇷🇴',
    'Ukraine': '🇺🇦',
    'Russia': '🇷🇺',
    'Egypt': '🇪🇬',
    'Morocco': '🇲🇦',
    'Tunisia': '🇹🇳',
    'Algeria': '🇩🇿',
    'Nigeria': '🇳🇬',
    'South-Africa': '🇿🇦',
    'Ghana': '🇬🇭',
    'Senegal': '🇸🇳',
    'Cameroon': '🇨🇲',
    'Colombia': '🇨🇴',
    'Chile': '🇨🇱',
    'Peru': '🇵🇪',
    'Uruguay': '🇺🇾',
    'Paraguay': '🇵🇾',
    'Ecuador': '🇪🇨',
    'Bolivia': '🇧🇴',
    'Venezuela': '🇻🇪',
    'India': '🇮🇳',
    'Ireland': '🇮🇪',
    'Wales': '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
    'Hungary': '🇭🇺',
    'Bulgaria': '🇧🇬',
    'Israel': '🇮🇱',
    'Cyprus': '🇨🇾',
    'Iceland': '🇮🇸',
    'Albania': '🇦🇱',
    'Slovenia': '🇸🇮',
    'Slovakia': '🇸🇰',
    'Bosnia-Herzegovina': '🇧🇦',
    'Montenegro': '🇲🇪',
    'North-Macedonia': '🇲🇰',
    'Georgia': '🇬🇪',
    'Armenia': '🇦🇲',
    'Azerbaijan': '🇦🇿',
    'Kazakhstan': '🇰🇿',
    'Uzbekistan': '🇺🇿',
    'Iran': '🇮🇷',
    'Iraq': '🇮🇶',
    'UAE': '🇦🇪',
    'Qatar': '🇶🇦',
    'Bahrain': '🇧🇭',
    'Kuwait': '🇰🇼',
    'Oman': '🇴🇲',
    'Jordan': '🇯🇴',
    'Thailand': '🇹🇭',
    'Vietnam': '🇻🇳',
    'Indonesia': '🇮🇩',
    'Malaysia': '🇲🇾',
    'Singapore': '🇸🇬',
    'Costa-Rica': '🇨🇷',
    'Honduras': '🇭🇳',
    'El-Salvador': '🇸🇻',
    'Guatemala': '🇬🇹',
    'Panama': '🇵🇦',
    'Jamaica': '🇯🇲',
    'Kenya': '🇰🇪',
    'Tanzania': '🇹🇿',
    'Ethiopia': '🇪🇹',
    'Congo-DR': '🇨🇩',
    'Congo': '🇨🇬',
    'Mali': '🇲🇱',
    'Burkina-Faso': '🇧🇫',
    'Guinea': '🇬🇳',
    'Togo': '🇹🇬',
    'Benin': '🇧🇯',
    'Niger': '🇳🇪',
    'Rwanda': '🇷🇼',
    'Uganda': '🇺🇬',
    'Zambia': '🇿🇲',
    'Zimbabwe': '🇿🇼',
    'Mozambique': '🇲🇿',
    'Angola': '🇦🇴',
    'Libya': '🇱🇾',
    'Sudan': '🇸🇩',
    'New-Zealand': '🇳🇿',
    'Northern-Ireland': '🇬🇧',
    'Luxembourg': '🇱🇺',
    'Malta': '🇲🇹',
    'Estonia': '🇪🇪',
    'Latvia': '🇱🇻',
    'Lithuania': '🇱🇹',
    'Moldova': '🇲🇩',
    'Belarus': '🇧🇾',
    'Faroe-Islands': '🇫🇴',
    'Kosovo': '🇽🇰',
    'Liechtenstein': '🇱🇮',
    'Andorra': '🇦🇩',
    'San-Marino': '🇸🇲',
    'Gibraltar': '🇬🇮',
  };

  static String flag(String leagueName) {
    for (final entry in _leagueFlags.entries) {
      if (leagueName.contains(entry.key)) return entry.value;
    }
    return '⚽';
  }

  static String countryFlag(String country) {
    return _countryFlags[country] ?? '🏳️';
  }

  /// Translate API-Football country names to French display
  static String countryDisplayName(String country) {
    const translations = {
      'England': 'Angleterre',
      'Spain': 'Espagne',
      'Germany': 'Allemagne',
      'Italy': 'Italie',
      'France': 'France',
      'Portugal': 'Portugal',
      'Netherlands': 'Pays-Bas',
      'Belgium': 'Belgique',
      'Turkey': 'Turquie',
      'Scotland': 'Ecosse',
      'USA': 'Etats-Unis',
      'Mexico': 'Mexique',
      'Brazil': 'Br\u00e9sil',
      'Argentina': 'Argentine',
      'Australia': 'Australie',
      'Japan': 'Japon',
      'South-Korea': 'Cor\u00e9e du Sud',
      'Saudi-Arabia': 'Arabie Saoudite',
      'China': 'Chine',
      'Ivory Coast': "C\u00f4te d'Ivoire",
      'World': 'International',
      'Europe': 'Europe',
      'Africa': 'Afrique',
      'South-America': 'Am\u00e9rique du Sud',
      'North-Central-America': 'Am\u00e9rique Centrale',
      'Asia': 'Asie',
      'Greece': 'Gr\u00e8ce',
      'Switzerland': 'Suisse',
      'Austria': 'Autriche',
      'Denmark': 'Danemark',
      'Norway': 'Norv\u00e8ge',
      'Sweden': 'Su\u00e8de',
      'Finland': 'Finlande',
      'Poland': 'Pologne',
      'Czech-Republic': 'Tch\u00e9quie',
      'Croatia': 'Croatie',
      'Serbia': 'Serbie',
      'Romania': 'Roumanie',
      'Ukraine': 'Ukraine',
      'Russia': 'Russie',
      'Egypt': 'Egypte',
      'Morocco': 'Maroc',
      'Tunisia': 'Tunisie',
      'Algeria': 'Alg\u00e9rie',
      'Nigeria': 'Nig\u00e9ria',
      'South-Africa': 'Afrique du Sud',
      'Ghana': 'Ghana',
      'Senegal': 'S\u00e9n\u00e9gal',
      'Cameroon': 'Cameroun',
      'Colombia': 'Colombie',
      'Ireland': 'Irlande',
    };
    return translations[country] ?? country;
  }
}
